### ISSUE TITLE
Replace TOML with YAML

### ISSUE THREAD

**Issue by rkatic** [blazing-edge-labs/api-skeleton#9]
TOML is more limited. A little too much limited (can not express any JSON structure.)

YAML is much more powerful, and the de facto standard language for configurations.

**Comment by PetarIvancevic** [comment]
We are basically using `toml` for simple strings and numbers. Still haven't had the need for a bigger structure.

**Comment by rkatic** [comment]
Although there where few occasions where I wanted TOML to be a little more powerful, I also see it's limitations as a feature, where it's kinda impossible with it to go crazy with app configurations.

If someone else didn't find TOML simplicity too limiting, I'm off idea to close this for now.
